### ISSUE TITLE
Support for Manufacturer enum “Apple”

### ISSUE THREAD

**Issue by frogg** [FitnessKit/AntMessageProtocol#1]
I just saw the list of available manufacturers in [ManufacturerExtension.swift](https://github.com/FitnessKit/AntMessageProtocol/blob/f6cfe1dfaba5ac8ae67c04593f0042961923afce/Sources/ANTMessageProtocol/Types/Manufacturer/ManufacturerExtension.swift).

And I was wondering what the procedure would be to add a new Manufacturer here?
I want to generate a `.fit` file from a workout session from my climbing fitness tracker Redpoint so I can upload the result to Strava. Since the sessions are recorded on Apple Watch I'd like to set the manufacturer to "Apple".

**Comment by khoogheem** [comment]
Those are IDs from ANT, which you have to become a member and then get the ID.
So until Apple Does that there won't be one for them and I doubt that will happen anytime soon.

Other Application such as VirtuGo have done this process, so you could thing about that. Otherwise I would recommend you use `255` development.
